services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: nuitinfo24-web-prod
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    environment:
      DJANGO_SETTINGS_MODULE: nuitinfo24.settings.production
      CACHE_HOST: cache
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      HOSTNAME: ${HOSTNAME}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - cache
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: nuitinfo24-postgre-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    restart: unless-stopped
  nginx:
    image: nginx:1.26.2
    container_name: nuitinfo24-nginx-prod
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80"
    depends_on:
      - web
    networks:
      - default
      - proxy-network
    restart: unless-stopped
  cache:
    image: redis:latest
    container_name: nuitinfo24-redis-prod
    expose:
      - 6379
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  proxy-network:
    name: proxy-network
    external: true
