services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile.dev
    container_name: nuitinfo24-web-dev
    volumes:
      - ./app:/usr/src/app
    expose:
      - 8000
    env_file:
      - ./.env
  db:
    image: postgres:15
    container_name: nuitinfo24-postgre-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    image: nginx:1.26.2
    container_name: nuitinfo24-nginx-dev
    volumes:
      - ./app/static:/usr/src/app/static
      - ./app/staticfiles:/usr/src/app/staticfiles
      - ./app/media:/usr/src/app/media
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
    depends_on:
      - web
      - db

volumes:
  postgres_data: