"""
Django settings for nuitinfo project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

INSTALLED_APPS = [
    "django.contrib.auth",
    "admin_interface",
    "colorfield",
    "django.contrib.admin",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "custom_error.apps.CustomErrorConfig",
    "core.apps.CoreConfig",
    'django_extensions',
    'fontawesome_5',
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

ROOT_URLCONF = "nuitinfo.urls"

LOGOUT_REDIRECT_URL = "/"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "nuitinfo.wsgi.application"

LANGUAGE_CODE = "fr-FR"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = False

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

ALLOWED_HOSTS = json.loads(os.environ["ALLOWED_HOSTS"])

HOSTNAME = os.getenv("HOSTNAME")

CORS_ALLOWED_ORIGINS = json.loads(os.environ["CORS_ALLOWED_ORIGINS"])

CSRF_TRUSTED_ORIGINS = json.loads(os.environ["CSRF_TRUSTED_ORIGINS"])

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    "static",
]
STATIC_ROOT = os.path.join(BASE_DIR.parent, "staticfiles")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR.parent, "media")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

sys.path.append(os.path.join(BASE_DIR.parent, "apps"))


# secure htts 1 week
SECURE_HSTS_SECONDS = 604800  # it is to enable the HSTS policy for 1 week
SESSION_COOKIE_AGE = 604800  # it is to set the session cookie age to 1 week
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # it is to include all subdomains in the HSTS policy
SECURE_HSTS_PRELOAD = True  # it is to include the site in the HSTS preload list
SECURE_REFERRER_POLICY = "same-origin"  # it is to send the Referer header only to the same origin
SECURE_BROWSER_XSS_FILTER = True  # it is to enable the XSS filter in the browser
SECURE_CONTENT_TYPE_NOSNIFF = True  # it is to prevent the browser from guessing the content type
SECURE_SSL_REDIRECT = True  # it is to redirect all HTTP requests to HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")  # it is to tell Django to trust the X-Forwarded-Proto header that comes from the proxy


CSRF_FAILURE_VIEW = "custom_error.views.ui_handler403_csrf"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": "db",
        "PORT": os.getenv("DB_PORT"),
    }
}
