# Generated by Django 5.1.3 on 2024-12-05 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokecoin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("valeur", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Succe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("coeur", models.BooleanField(default=False)),
                ("poumon", models.BooleanField(default=False)),
                ("foie", models.BooleanField(default=False)),
                ("rein", models.BooleanField(default=False)),
                ("utilisateur", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ProfilePokecoin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pokecoin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.pokecoin")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.profile")),
            ],
            options={
                "unique_together": {("profile", "pokecoin")},
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="pokecoin",
            field=models.ManyToManyField(blank=True, through="core.ProfilePokecoin", to="core.pokecoin"),
        ),
        migrations.CreateModel(
            name="ProfileSucce",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.profile")),
                ("succe", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.succe")),
            ],
            options={
                "unique_together": {("profile", "succe")},
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="succes",
            field=models.ManyToManyField(blank=True, through="core.ProfileSucce", to="core.succe"),
        ),
    ]
